[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/payment-success"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
